---
apiVersion: v1
data:
  secret-access-key: MlNZWG1RUUc2MnQ0bld2WlJPQjNhQ0dac04rQnk0TXBLNVJ6MUJRSQ== 
kind: Secret
metadata:
  name: route53-credentials-secret
  namespace: cert-manager 
type: Opaque
